name: ios-ci

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: unit-tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        run: |
          device=$(xcrun simctl list devices available | grep "iPhone" | head -1 | awk -F '(' '{print $1}' | xargs)

          xcodebuild test \
            -project MVVMDemo.xcodeproj \
            -scheme MVVMDemo \
            -destination "platform=iOS Simulator,name=$device"
