name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Scheme
        run: echo "MVVMDemo" > default

      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          device=$(xcrun simctl list devices available | grep "iPhone" | head -1 | awk -F '(' '{print $1}' | xargs)
          scheme=$(cat default)

          xcodebuild build-for-testing \
            -project MVVMDemo.xcodeproj \
            -scheme "$scheme" \
            -destination "platform=iOS Simulator,name=$device"

      - name: Test
        env:
          scheme: ${{ 'default' }}
        run: |
          device=$(xcrun simctl list devices available | grep "iPhone" | head -1 | awk -F '(' '{print $1}' | xargs)
          scheme=$(cat default)

          xcodebuild test-without-building \
            -project MVVMDemo.xcodeproj \
            -scheme "$scheme" \
            -destination "platform=iOS Simulator,name=$device" \
            -only-testing:MVVMDemoTests
